name: FanLiv Playlist Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Source
        run: |
          curl -L "${{ secrets.SRCFANLIV }}" -o source.m3u

      - name: Clean Playlist
        run: |
          sed -n '/#EXTM3U/,$p' source.m3u | grep -E '^#EXTM3U|^#EXTINF|^http' > fanliv.m3u

      - name: Commit if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add fanliv.m3u
          git diff --cached --quiet || git commit -m "Auto update FanLiv playlist"
          git push
