name: GeoSitaraplus JioTV Auto Fix

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Download Source Playlist
        run: |
          curl -sL "${{ secrets.SRCSITARAPLUS }}" -o source.m3u

      - name: Remove HTML Header
        run: |
          sed -n '/#EXTM3U/,$p' source.m3u > clean.m3u

      - name: Fix JioTV MPD + Refresh Cookie
        run: |
          awk '
          /#EXTHTTP/ {
            match($0, /cookie":"([^"]+)/, a)
            cookie=a[1]
            print
            next
          }

          /\.mpd/ {
            url=$0
            sub(/\?.*/, "", url)

            print url "?" cookie "&xxx=%7Ccookie=" cookie
            next
          }

          {print}
          ' clean.m3u > geyositaraplus.m3u

      - name: Commit Update
        run: |
          git add geyositaraplus.m3u
          git diff --cached --quiet || git commit -m "Auto fix JioTV MPD + refresh cookie"
          git push
