name: Build Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # -------- JSON → M3U --------
      - name: Download JSON
        run: |
          curl -L "${{ secrets.SRCFKODE }}?t=$(date +%s)" -o src.json

      - name: Convert JSON to M3U
        run: |
          echo "#EXTM3U" > Kashmir.m3u
          jq -r '.[] |
          "#EXTINF:-1 tvg-name=\"" + .name + "\" tvg-logo=\"" + .logo + "\"," + .name,
          "#KODIPROP:inputstream.adaptive.license_type=" + .drmScheme,
          "#KODIPROP:inputstream.adaptive.license_key=" + .drmLicense,
          "#EXTVLCOPT:http-user-agent=plaYtv/7.1.3 (Linux;Android 13)",
          "#EXTHTTP:{\"cookie\":\"" + .cookie + "\"}",
          (.link + "?" + .cookie + "&xxx=%7Ccookie=" + .cookie)' src.json >> Kashmir.m3u

      # -------- SECOND SOURCE M3U --------
      - name: Download Second M3U
        run: |
          curl -L "${{ secrets.SRCSTAR }}?t=$(date +%s)" -o extra_playlist_new.m3u

      - name: Check if playlist changed
        run: |
          if [ -f extra_playlist.m3u ]; then
            if cmp -s extra_playlist.m3u extra_playlist_new.m3u; then
              echo "No change in playlist"
              rm extra_playlist_new.m3u
            else
              mv extra_playlist_new.m3u extra_playlist.m3u
            fi
          else
            mv extra_playlist_new.m3u extra_playlist.m3u
          fi

      - name: Commit playlists
        run: |
          git add Kashmir.m3u extra_playlist.m3u
          git diff --cached --quiet || git commit -m "Auto update playlists"
          git push
